### ISSUE TITLE
Breadcrumb does not always dynamically resize

### ISSUE THREAD

**Issue by jaspalsinghsaini** [rgerd/SwitchSpeak#50]
As we add more phrases to the sentence being formed, the breadcrumb dynamically resizes to ensure that the current sentence fits within one line. And if we press multiple "oops" buttons to remove some of the top elements from the breadcrumb we would expect it to resize again. However, the breadcrumb size does not change when "oops" is pressed.

**Comment by rgerd** [comment]
This happens because the button dimensions are [updated in `CrumbManager.push`](https://github.com/rgerd/SwitchSpeak/blob/master/SwitchSpeak-iOS/SwitchSpeak-iOS/TouchGrid/CrumbManager.swift#L120) but not in [`CrumbManager.pop`](https://github.com/rgerd/SwitchSpeak/blob/master/SwitchSpeak-iOS/SwitchSpeak-iOS/TouchGrid/CrumbManager.swift#L87-L94). Easiest fix while preserving clean code would be to move [this code](https://github.com/rgerd/SwitchSpeak/blob/master/SwitchSpeak-iOS/SwitchSpeak-iOS/TouchGrid/CrumbManager.swift#L115-L123) into a private function in CrumbManager called `updateUILayout` or something, replace [that code](https://github.com/rgerd/SwitchSpeak/blob/master/SwitchSpeak-iOS/SwitchSpeak-iOS/TouchGrid/CrumbManager.swift#L115-L123) with a call to the new function, slip the new function into [here](https://github.com/rgerd/SwitchSpeak/blob/master/SwitchSpeak-iOS/SwitchSpeak-iOS/TouchGrid/CrumbManager.swift#L90-L91), and call it a day.

Note: [See this loop](https://github.com/rgerd/SwitchSpeak/blob/master/SwitchSpeak-iOS/SwitchSpeak-iOS/TouchGrid/Tree/Node.swift#L73) for an example of how to write [this loop](https://github.com/rgerd/SwitchSpeak/blob/master/SwitchSpeak-iOS/SwitchSpeak-iOS/TouchGrid/CrumbManager.swift#L119) better, so that you don't have to initialize and increment that `index` variable.

**Comment by rgerd** [comment]
Merged PR #51 solving this issue.
